version: '3.8'

services:
  elasticsearch-kibana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch-kibana-container
    ports:
      - "9200:9200"
      - "5601:5601"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
